*"*"Lokale Schnittstelle:
*"  IMPORTING
*"     VALUE(OBJECTCLASS) LIKE  CDHDR-OBJECTCLAS
*"     VALUE(OBJECTID) LIKE  CDHDR-OBJECTID
*"     VALUE(PLANNED_CHANGE_NUMBER) LIKE  CDHDR-PLANCHNGNR DEFAULT
*"       SPACE
*"     VALUE(PLANNED_OR_REAL_CHANGES) LIKE  CDHDR-CHANGE_IND DEFAULT
*"       SPACE
*"  EXCEPTIONS
*"      SEQUENCE_INVALID


